### ISSUE TITLE
There is no release or instructions on how to use or install

### ISSUE THREAD

**Issue by TheSeanLavery** [jayanam/jmesh-tools#12]
It would be nice if there were a release in the release tab along with instructions on how to install the plugin.

**Comment by jayanam** [comment]
Ok thx, will be added next week

**Comment by raindropsfromsky** [comment]
Since the tool has seen many changes since it was introduced, it is best to describe it afresh, rather than talking only about new features.

Over the time, each section has grown strong, and it can be used independently (to me, this Addon looks like a combination of three separate Addons, which can be used independently; and sometimes together.)

Another request: So far, I have seen you build a single complex piece to demonstrate the capabilities of the Addon. The problem with that approach is that you do not need the various parts of the Addon in left-to-right, top-to-bottom order. So, while the user enjoys the demo, he does not get the feel of each part of the Addon.

We need a demo that takes the user for a walk through the tool. 

This can be done if you take a section and demonstrate its commands using specially built objects.
Depending upon the nature of the tool, it may need one or more objects.

With this approach, the user will become very comfortable in using the tool himself. He will also know what to do, and what to avoid (when the tool does not work).

**Comment by jayanam** [comment]
Main issue is fixed, will also come up with basic tutorials and articles on my website.
